version: '3.8'

services:
  djangoapp:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env.dev
    depends_on:
      - db
    entrypoint:
      - /usr/src/app/entrypoint.sh
    ports:
      - 8000:8000
    command: bash -c "cd /usr/src/app/app/ && python manage.py runserver 0.0.0.0:8000"
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: